apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubenest-workload.fullname" . }}
  labels:
    {{- include "kubenest-workload.labels" . | nindent 4 }}
    kubenest.io/component: main
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "kubenest-workload.selectorLabels" . | nindent 6 }}
      kubenest.io/component: main
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.secret.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.deployment.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kubenest-workload.selectorLabels" . | nindent 8 }}
        kubenest.io/component: main
        {{- with .Values.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubenest-workload.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.container.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.container.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ include "kubenest-workload.portName" . }}
              containerPort: {{ .Values.container.port }}
              protocol: TCP
            {{- with .Values.container.additionalPorts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.container.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.container.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.container.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.container.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.container.startupProbe.enabled }}
          startupProbe:
            {{- omit .Values.container.startupProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.container.resources | nindent 12 }}
          {{- with .Values.container.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.container.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.configMap.mountPath .Values.secret.mountPath .Values.persistence.enabled }}
          volumeMounts:
            {{- if .Values.configMap.mountPath }}
            - name: config
              mountPath: {{ .Values.configMap.mountPath }}
            {{- end }}
            {{- if .Values.secret.mountPath }}
            - name: secret
              mountPath: {{ .Values.secret.mountPath }}
              readOnly: true
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
          {{- end }}
      {{- if or .Values.configMap.mountPath .Values.secret.mountPath .Values.persistence.enabled }}
      volumes:
        {{- if .Values.configMap.mountPath }}
        - name: config
          configMap:
            name: {{ include "kubenest-workload.fullname" . }}
        {{- end }}
        {{- if .Values.secret.mountPath }}
        - name: secret
          secret:
            secretName: {{ include "kubenest-workload.fullname" . }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "kubenest-workload.fullname" .) }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
